# add APIKEY and USERKEY as an environment variable - https://gitlab.com/help/ci/variables/README
default:
  image: maven:3.8-openjdk-11

stages:
  - build
  - scan

## Maven example - replace with your builds steps
maven_build:
  image: maven:3.8.4-eclipse-temurin-17-alpine
  stage: build
  script: "mvn clean install -DskipTests"
  
cache:
  key: "cache-$MVN_PKG-$CI_PIPELINE_ID"
  paths:
  - ${CI_PROJECT_DIR}/
## end maven build example

# The Unified Agent scan should be called AFTER a package manager build step such as "mvn clean install -DskipTests=true" or "npm install --only=prod"
mend_scan:
  stage: scan
  variables:
    WS_APIKEY: $API_KEY
    WS_USERKEY: $USER_KEY
    WS_MAVEN_AGGREGATEMODULES: "true"
    WS_WSS_URL: "https://saas.mend.io/agent"
    WS_PRODUCTNAME: $CI_PROJECT_NAME
    WS_PROJECTNAME: $CI_COMMIT_REF_NAME
    WS_FILESYSTEMSCAN: "false"
  script: |
    echo "Downloading Mend Unified Agent"
    curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
    if [[ "$(curl -sL https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar.sha256)" != "$(sha256sum wss-unified-agent.jar)" ]] ; then
      echo "Integrity Check Failed"
    else
      echo "Integrity Check Passed"
      echo Starting Mend Scan
      java -jar wss-unified-agent.jar
    fi

