# ******** Mend Unified CLI Template for CircleCI ********
#
# You may wish to alter this file to override the build tool and the Mend scanning technologies used (SCA, SAST or Conatiner).
#
# For more configeration options, please check the technical documentation portal:
# 📚 https://docs.mend.io/bundle/cli/page/scan_with_mend_s_unified_cli.html 
#
# ******** Description ********
# Mend SCA will automatically use package managers and file system scanning to detect open source components. 
# Mend SAST will automatically detect languages and frameworks used in your projects to scan for code weaknesses.

# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  node: circleci/node@4.7.0
  # maven: circleci/maven@1.4.1
jobs:
  example-mend-job:
    steps:
      ## checkout git
      # - checkout
      ## install node/npm
      # - node/install
      ## npm install packages
      # - node/install-packages
      ## 
      ## - maven install
      # - maven/install:
      #    command: '-DskipTests'
      # execute Mend scan, curling Mend CLI. Remember to set the following environmental variables:
      ### SCA Environment Variables ###
      # MEND_EMAIL
      # MEND_USER_KEY
      # MEND_URL
      ### SAST Environment Variables ###
      # MEND_SAST_SERVER_URL
      # MEND_SAST_API_TOKEN
      # MEND_SAST_ORGANIZATION
# The Mend SCA CLI scan should be called AFTER a package manager build step such as "mvn clean install -DskipTests=true" or "npm install --only=prod"
      - run: 
          name: Download Mend CLI
          command: bash <(curl https://downloads.mend.io/production/unified/latest/linux_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend)
      - run: 
          name: Run Mend dependencies (SCA) scan
          command: mend deps -u
      - run: 
          name: Run Mend code (SAST) scan
          command: mend code
workflows:
  example-workflow:
    jobs:
      - example-mend-job
