# ******** Mend Unified CLI Template for Bitbucket CI ********
#
# You may wish to alter this file to override the build tool and the Mend scanning technologies used (SCA, SAST or Conatiner).
#
# For more configeration options, please check the technical documentation portal:
# 📚 https://docs.mend.io/bundle/cli/page/scan_with_mend_s_unified_cli.html 
#
# ******** Description ********
# Mend SCA will automatically use package managers and file system scanning to detect open source components. 
# Mend SAST will automatically detect languages and frameworks used in your projects to scan for code weaknesses.

# The user needs to set up enviroment variables in Bitbucket CI, see here for more inforamtion: https://support.atlassian.com/bitbucket-cloud/docs/variables-and-secrets/
# The environment variables are:
### SCA Environment Variables ###
# MEND_EMAIL: MEND_SCA_EMAIL
# MEND_USER_KEY: MEND_SCA_USERKEY
# MEND_URL: https://saas.mend.io
### SAST Environment Variables ###
# MEND_SAST_SERVER_URL: https://saas.mend.io/sast
# MEND_SAST_API_TOKEN: MEND_SAST_API
# MEND_SAST_ORGANIZATION: MEND_SAST_ORGANIZATION


image: atlassian/default-image:latest
  
pipelines:
  default:
  # Build steps
    # - step:
    #     name: NPM Build
    #     name: Maven Install
    #     name: Dotnet Restore
# The Mend SCA CLI scan should be called AFTER a package manager build step such as "mvn clean install -DskipTests=true" or "npm install --only=prod"
# Mend CLI
    - step:
        name: Mend CLI Scan
        script:
        - |
          echo Downloading Mend CLI
          curl -LJO https://downloads.mend.io/production/unified/latest/linux_amd64/mend && chmod +x mend
          ### dependencies (SCA) Scan ###
          echo Start Mend dependencies (SCA) scan
          ./mend deps -u
          ### code (SAST) Scan ###
          echo Start Mend code (SAST) scan
          ./mend code